refactor: refactor xdk
linkall-labs/cdk-java pull request #67
Opened 2022-12-12 11:12 UTC by xdlbdy

**Changes:**
-

2022-12-14 18:06 UTC, wenfengwang requested changes

2022-12-14 18:06 UTC, wenfengwang commented on core/src/main/java/com/linkall/vance/core/VanceApplication.java
>  public class VanceApplication {
rename to `VanceApplication`?

2022-12-14 18:06 UTC, wenfengwang commented on core/src/main/java/com/linkall/vance/store/KVStore.java
> +    void put(String key, byte[] value) throws Exception;
set?

2022-12-14 18:07 UTC, wenfengwang commented
Here are two need to disscuss:
1. change `core` to `runtime` in order to keep same with cdk-go
2. change package to `com.linkall.cdk`

2022-12-16 08:07 UTC, xdlbdy commented on core/src/main/java/com/linkall/vance/core/VanceApplication.java
>  public class VanceApplication {
do you mean Application?

2022-12-16 08:41 UTC, wenfengwang approved these changes
LGTM

2022-12-16 08:42 UTC, merged